
<html>
<head> <link rel="canonical" href="http://www.mcs.anl.gov/petsc/petsc-current/src/mat/examples/tutorials/makefile.html" />
<title></title>
<meta name="generator" content="c2html 0.9.4">
<meta name="date" content="2019-09-30T00:22:33+00:00">
</head>

<body bgcolor="#FFFFFF">
   <div id="version" align=right><b>petsc-3.12.0 2019-09-29</b></div>
   <div id="bugreport" align=right><a href="mailto:petsc-maint@mcs.anl.gov?subject=Typo or Error in Documentation &body=Please describe the typo or error in the documentation: petsc-3.12.0 v3.12 src/mat/examples/tutorials/makefile.html "><small>Report Typos and Errors</small></a></div>
<pre width="80">
CFLAGS 	        =
FFLAGS	        =
CPPFLAGS        =
FPPFLAGS        =
LOCDIR          = src/mat/examples/tutorials/
EXAMPLESC       = ex1.c ex2.c ex4.c ex8.c ex9.c ex10.c ex11.c ex12.c ex15.c ex16.c ex17.c
EXAMPLESF       = ex4f.F90 ex6f.F90 ex15f.F90 ex17f.F90
MANSEC          = <a href="ROOT/docs/manualpages/Mat/Mat.html#Mat">Mat</a>

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

</pre>
</body>

</html>
