
<html>
<head> <link rel="canonical" href="http://www.mcs.anl.gov/petsc/petsc-current/src/vec/vec/examples/tutorials/makefile.html" />
<title></title>
<meta name="generator" content="c2html 0.9.4">
<meta name="date" content="2019-09-29T23:59:43+00:00">
</head>

<body bgcolor="#FFFFFF">
   <div id="version" align=right><b>petsc-3.12.0 2019-09-29</b></div>
   <div id="bugreport" align=right><a href="mailto:petsc-maint@mcs.anl.gov?subject=Typo or Error in Documentation &body=Please describe the typo or error in the documentation: petsc-3.12.0 v3.12 src/vec/vec/examples/tutorials/makefile.html "><small>Report Typos and Errors</small></a></div>
<pre width="80"><font color="#A020F0">#</font>
CFLAGS		 =
FFLAGS		 =
CPPFLAGS         =
FPPFLAGS         =
MANSEC           = <a href="ROOT/docs/manualpages/Vec/Vec.html#Vec">Vec</a>
LOCDIR		 = src/vec/vec/examples/tutorials/
EXAMPLESC	 = ex1.c ex2.c ex3.c ex5.c ex6.c ex7.c ex8.c ex9.c ex10.c \
                   ex11.c ex12.c ex15.c ex16.c ex18.c ex19.c ex42.c ex42a.c ex21.c ex43.c
EXAMPLESF	 = ex1f.F90 ex1f90.F90 ex2f.F ex3f.F ex4f.F ex4f90.F90 ex5f.F90 ex6f.F90 ex9f.F90 \
                   ex11f.F ex11f90.F90 ex12f.F90 ex14f.F90 ex16f.F90 ex20f90.F90 ex21f90.F90 ex43f.F90

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

<strong><font color="#FF0000">ex7:</font></strong> ex7.o ex7f.o
<strong><font color="#FF0000">ex21f90:</font></strong> ex21f90.o ex21.o
<strong><font color="#FF0000">ex43f:</font></strong> ex43.o ex43f.o
</pre>
</body>

</html>
